workflows:
  ios-build:
    name: Build iOS without Apple Account
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      vars:
        APP_ID: "com.yonatan.taskapp"
        APP_NAME: "task-manager-client"
      node: 18
    scripts:
      - name: 📦 Install dependencies
        script: |
          npm install
      - name: 🛠 Build Vite app
        script: |
          npm run build
      - name: ➕ Sync Capacitor
        script: |
          npx cap sync ios
      - name: 🧪 Open iOS project
        script: |
          cd ios && pod install
    artifacts:
      - ios/build/**/*
